export enum ChartActionTypes {
  CHARTS_INIT         = '[FRNDS APP CHARTS] FRNDS CHARTS INIT',
  CHARTS_LOAD_SUCCESS = '[FRNDS APP CHARTS] FRNDS CHARTS SUCCESS',
  CHARTS_LOAD_FAILURE = '[FRNDS APP CHARTS] FRNDS CHARTS FAILURE'
}
