export enum UserActionTypes {
  USER_INIT         = '[Users page] Init',
  USER_CREATE       = '[Users page] CREATE',
  USER_UPDATE       = '[Users page] UPDATE',
  USER_DELETE       = '[Users page] DELETE',
  USER_CANCEL       = '[Users page] CANCEL',
  USER_SELECT_USER  = '[Users page] SELECT USER',
  USER_GET_ALL      = '[Users/API] GET ALL USERS',
  USER_GET_BY_ID    = '[Users/API] GET BY ID',
  USER_GET_BY_QUERY = '[Users/API] GET BY QUERY',
  USER_CREATE_USER  = '[Users/API] CREATE USER',
  USER_UPDATE_ID    = '[Users/API] UPDATE USER',
  USER_DELETE_ID    = '[Users/API] DELETE USER',
  USER_SUCCESS      = '[Users/API] SUCCESS',
  USER_ERROR        = '[Users/API] ERROR',
}
